export const PROGRAM_PAGES={
 hifz:{
  slug:"hifz" as const,kicker:"Online Hifz Program",title:"Online Hifz classes with a dedicated Qur'an teacher",arabic:"حِفْظُ الْقُرْآنِ",intro:"Memorize the Qur'an through structured one-to-one lessons, daily revision and personal guidance from an experienced teacher.",description:"Our online Hifz program gives each student an individual memorization and revision plan. Lessons follow a balanced Sabaq, Sabqi and Manzil routine so new memorization develops alongside strong long-term retention.",benefits:["A personalized Hifz and revision plan","Daily Sabaq, Sabqi and Manzil practice","Correction of recitation and memorization mistakes","Consistent progress suited to the student's pace"],audience:"Children, teenagers and adults",method:"Sabaq · Sabqi · Manzil",
  metaTitle:"Online Hifz Classes | Personal Qur'an Memorization Teacher",metaDescription:"Join one-to-one online Hifz classes with an experienced Qur'an teacher. Personalized Sabaq, Sabqi and Manzil plans for children and adults worldwide.",keywords:["online Hifz classes","Hifz teacher online","Quran memorization teacher","online Hifz tutor","Hifz classes for kids","Quran memorization classes","Hifz course online","female Hifz teacher online"]
 },
 nazra:{
  slug:"nazra" as const,kicker:"Online Nazra Program",title:"Learn to read the Qur'an online with a Nazra teacher",arabic:"تِلَاوَةُ الْقُرْآنِ نَظَرًا",intro:"Develop clear, confident and accurate Qur'an reading from letter recognition to fluent guided recitation.",description:"Our online Nazra Qur'an classes begin at the student's current level. A teacher provides direct correction in letter recognition, joining, vowel marks and fluent reading, with Noorani Qaida foundations where needed.",benefits:["Recognition and correct joining of Arabic letters","Vowel marks and foundational reading rules","Noorani Qaida guidance where required","Fluent Qur'an reading with direct correction"],audience:"Beginners, children and adult learners",method:"Noorani Qaida to fluent Nazra",
  metaTitle:"Online Nazra Quran Classes | Learn Quran Reading Online",metaDescription:"Learn to read the Qur'an with one-to-one online Nazra classes. Noorani Qaida, Arabic letters, vowel marks and fluent Quran reading for kids and adults.",keywords:["online Nazra Quran classes","Nazra Quran teacher online","learn Quran reading online","online Quran reading teacher","Noorani Qaida classes online","Quran classes for beginners","online Quran classes for kids","Nazra Quran course"]
 },
 tajweed:{
  slug:"tajweed" as const,kicker:"Online Tajweed Program",title:"Online Tajweed classes for accurate Qur'an recitation",arabic:"تَجْوِيدُ الْقُرْآنِ",intro:"Improve pronunciation, rhythm and confidence through individual Tajweed lessons with direct recitation correction.",description:"Our online Tajweed classes focus on practical recitation. Students study Makharij al-Huruf, essential Sifat and applied Tajweed rules while reading directly to a teacher who identifies and corrects mistakes.",benefits:["Correct Makharij al-Huruf and pronunciation","Practical understanding of essential Sifat","Applied rules including Madd, Ghunnah, Idgham and Ikhfa","More fluent and confident Qur'an recitation"],audience:"Beginners and improving reciters",method:"Theory with guided recitation practice",
  metaTitle:"Online Tajweed Classes | Learn Quran Recitation with a Teacher",metaDescription:"Improve your Qur'an recitation through one-to-one online Tajweed classes. Learn Makharij, Sifat and practical Tajweed rules with direct teacher correction.",keywords:["online Tajweed classes","Tajweed teacher online","learn Tajweed online","Quran recitation classes","online Quran tutor Tajweed","Makharij classes online","Tajweed course for adults","Tajweed classes for kids"]
 }
};
