import type { Metadata } from "next";
import Link from "next/link";
import { Footer, Header } from "@/components/SiteChrome";
import { ENROLL_WHATSAPP_URL } from "@/lib/contact";

const title="Online Quran Classes for Kids & Adults | Learn Quran Online";
const description="Find one-to-one online Quran classes in Hifz, Nazra and Tajweed for kids and adults. Learn with experienced Quran teachers through flexible live lessons.";
export const metadata:Metadata={
 title,description,
 keywords:["online Quran classes","learn Quran online","online Quran teacher","Quran tutor online","online Quran academy","online Quran institute","Quran classes for kids","Quran classes for adults","female Quran teacher online","one to one Quran classes","Hifz classes online","Nazra Quran classes","Tajweed classes online","Noorani Qaida online","Quran lessons online Pakistan"],
 alternates:{canonical:"/online-quran-classes"},
 openGraph:{title,description,url:"/online-quran-classes",type:"website"},twitter:{card:"summary_large_image",title,description}
};
const courses=[
 {name:"Online Hifz Classes",url:"/hifz",text:"Personal memorization plans with Sabaq, Sabqi and Manzil revision."},
 {name:"Online Tajweed Classes",url:"/tajweed",text:"Practical Makharij, Sifat and recitation correction with a teacher."},
 {name:"Online Nazra Quran Classes",url:"/nazra",text:"Noorani Qaida foundations through fluent and accurate Quran reading."}
];
export default function Page(){
 const schema={"@context":"https://schema.org","@type":"EducationalOrganization",name:"Markaz Al Murtaza Al Islami & Safia Islamic Institute",url:"https://markazulmurtaza.vercel.app/online-quran-classes",hasOfferCatalog:{"@type":"OfferCatalog",name:"Online Quran Courses",itemListElement:courses.map(course=>({"@type":"Course",name:course.name,description:course.text,url:`https://markazulmurtaza.vercel.app${course.url}`,provider:{"@type":"EducationalOrganization",name:"Markaz Al Murtaza Al Islami & Safia Islamic Institute"}}))}};
 return <><Header dark/><main><section className="online-quran-hero"><div><p className="kicker gold">One-to-one live learning</p><h1>Online Quran classes for kids and adults</h1><p>Learn Quran online through personal Hifz, Nazra and Tajweed lessons with experienced teachers, flexible scheduling and guidance suited to your level.</p><div className="hero-ctas"><a className="btn btn-light" href={ENROLL_WHATSAPP_URL} target="_blank" rel="noopener">Book a free trial</a><a className="btn btn-outline-light" href="#courses">Explore classes</a></div></div></section><section className="online-quran-intro"><p className="kicker">Find the right Quran teacher online</p><h2>A focused learning path, wherever you live.</h2><p>Markaz Al Murtaza Al Islami &amp; Safia Islamic Institute provides individual online Quran lessons for beginners, children, teenagers and adults. Each live class gives the learner direct attention, correction and a lesson plan based on their current reading or memorization level.</p></section><section className="online-course-grid" id="courses">{courses.map(course=><Link href={course.url} key={course.url}><span>Online program</span><h2>{course.name}</h2><p>{course.text}</p><strong>View program →</strong></Link>)}</section><section className="online-find"><div><p className="kicker">What learners can find here</p><h2>Quran learning from the foundations onward.</h2></div><ul><li>One-to-one online Quran classes</li><li>Quran lessons for children and adults</li><li>Noorani Qaida and beginner reading</li><li>Hifz memorization and revision</li><li>Tajweed, Makharij and recitation correction</li><li>Flexible class scheduling across time zones</li></ul></section><section className="online-faq"><p className="kicker">Common questions</p><h2>Choosing an online Quran institute</h2><details><summary>Can beginners join the online Quran classes?</summary><p>Yes. Lessons can begin with Arabic letters and Noorani Qaida before progressing to fluent Nazra Quran reading.</p></details><details><summary>Are classes available for both kids and adults?</summary><p>Yes. The learning pace and lesson plan are adapted to the student's age, experience and goals.</p></details><details><summary>Can I study Hifz or Tajweed online?</summary><p>Yes. Separate one-to-one programs are available for Hifz memorization, practical Tajweed and Nazra Quran reading.</p></details></section><section className="online-final"><h2>Start learning Quran online.</h2><p>Contact the institute to discuss your level, preferred program and schedule.</p><a className="btn btn-primary" href={ENROLL_WHATSAPP_URL} target="_blank" rel="noopener">Contact on WhatsApp</a></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main><Footer/></>;
}
