import type { Metadata } from "next";
import Link from "next/link";
import { Footer, Header } from "@/components/SiteChrome";
import { ENROLL_WHATSAPP_URL } from "@/lib/contact";

const title="Online Hifz and Tajweed Institute | One-to-One Quran Classes";
const description="Join an online Hifz and Tajweed institute for one-to-one Quran memorization, revision and recitation correction. Flexible classes for kids and adults.";
export const metadata:Metadata={title,description,keywords:["online Hifz and Tajweed institute","online Hifz and Tajweed classes","Hifz with Tajweed online","online Quran memorization institute","online Hifz teacher","online Tajweed teacher","Quran Hifz classes for kids","Tajweed classes for adults","one to one Quran classes","memorize Quran online with Tajweed","Quran memorization and recitation course"],alternates:{canonical:"/online-hifz-tajweed-institute"},openGraph:{title,description,url:"/online-hifz-tajweed-institute",type:"website"},twitter:{card:"summary_large_image",title,description}};
const faqs=[
 ["Can Hifz and Tajweed be studied together online?","Yes. Recitation is corrected as memorization develops, helping students avoid repeating pronunciation mistakes while learning new passages."],
 ["Are these classes suitable for children and adults?","Yes. The amount of new memorization, revision and Tajweed practice can be adjusted to the learner's age, level and available study time."],
 ["What happens in an online Hifz lesson?","A lesson can include new memorization, recent revision and older revision through the Sabaq, Sabqi and Manzil method, together with direct recitation correction."],
 ["Can a beginner start with Tajweed before Hifz?","Yes. Learners who need stronger reading foundations can begin with Nazra, pronunciation and practical Tajweed before starting a full memorization plan."]
];
export default function Page(){
 const schema={"@context":"https://schema.org","@graph":[{"@type":"Course",name:"Online Hifz and Tajweed Classes",description,provider:{"@type":"EducationalOrganization",name:"Markaz Al Murtaza Al Islami & Safia Islamic Institute",url:"https://markazulmurtaza.vercel.app"},hasCourseInstance:{"@type":"CourseInstance",courseMode:"Online"}},{"@type":"FAQPage",mainEntity:faqs.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))}]};
 return <><Header dark/><main><section className="ht-hero"><div><p className="kicker gold">Memorization with accurate recitation</p><h1>Online Hifz and Tajweed institute</h1><p>One-to-one Quran classes that combine structured memorization, consistent revision and practical Tajweed correction for children and adults.</p><div className="hero-ctas"><a href={ENROLL_WHATSAPP_URL} className="btn btn-light" target="_blank" rel="noopener">Book a free trial</a><a href="#method" className="btn btn-outline-light">See the learning method</a></div></div></section>
 <section className="ht-intro"><p className="kicker">A connected learning path</p><h2>Memorize the Quran without leaving correct recitation behind.</h2><p>Students searching for an online Hifz and Tajweed institute often need two forms of guidance at the same time: a reliable memorization routine and a teacher who listens carefully to every recited passage. Our one-to-one format brings both together. New memorization is supported by revision, while pronunciation and practical Tajweed are corrected during the lesson.</p></section>
 <section className="ht-split" id="method"><article><span>01</span><h2>Structured online Hifz</h2><p>The Hifz path uses a personal plan suited to the student's current level and pace. Sabaq develops new memorization, Sabqi reinforces recently learned passages, and Manzil protects older memorization through continued revision.</p><ul><li>Personal memorization targets</li><li>Sabaq, Sabqi and Manzil routine</li><li>Direct correction during recitation</li><li>Progress at a sustainable pace</li></ul><Link href="/hifz">Explore online Hifz classes →</Link></article><article><span>02</span><h2>Practical online Tajweed</h2><p>Tajweed instruction is applied to actual Quran recitation. The teacher helps the student improve Makharij al-Huruf, essential Sifat and rules such as Madd, Ghunnah, Idgham and Ikhfa without separating theory from practice.</p><ul><li>Makharij and letter pronunciation</li><li>Essential qualities of letters</li><li>Applied Tajweed rules</li><li>Fluency and recitation confidence</li></ul><Link href="/tajweed">Explore online Tajweed classes →</Link></article></section>
 <section className="ht-process"><div><p className="kicker">How online learning begins</p><h2>A clear route from assessment to consistent study.</h2></div><ol><li><strong>Discuss your goal</strong><span>Tell the institute whether you want to begin Hifz, improve Tajweed, or combine both.</span></li><li><strong>Check your current level</strong><span>Your reading, pronunciation and memorization needs guide the starting point.</span></li><li><strong>Follow a personal routine</strong><span>Attend one-to-one lessons and practise the assigned memorization and revision between classes.</span></li></ol></section>
 <section className="ht-audience"><p className="kicker">Who the program serves</p><h2>Online Quran instruction adapted to the learner.</h2><div><article><h3>Children</h3><p>Manageable memorization portions, repeated correction and a routine parents can support from home.</p></article><article><h3>Adults</h3><p>Flexible progress for learners balancing Quran study with work, family and other commitments.</p></article><article><h3>Improving reciters</h3><p>Focused Tajweed correction before or alongside memorization to strengthen accuracy and confidence.</p></article></div></section>
 <section className="ht-faq"><p className="kicker">Frequently asked questions</p><h2>Online Hifz and Tajweed classes</h2>{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>
 <section className="online-final"><h2>Begin your Hifz and Tajweed journey online.</h2><p>Contact Markaz Al Murtaza Al Islami &amp; Safia Islamic Institute to discuss the right starting point.</p><a href={ENROLL_WHATSAPP_URL} className="btn btn-primary" target="_blank" rel="noopener">Contact on WhatsApp</a></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main><Footer/></>;
}
