"use client";
import { useMemo, useState } from "react";
import { Footer, Header } from "./SiteChrome";
import { useI18n } from "./I18nProvider";
import { sitePath } from "@/lib/site-path";
const amounts=[1000,5000,10000,25000,50000];

function CopyIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M4 15V6a2 2 0 0 1 2-2h9"/></svg>}
function HeartIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden><path d="M12 21s-7.5-4.7-9.5-9C1 8.5 3 5 6.5 5c2 0 3.5 1 4.5 2.5C12 6 13.5 5 15.5 5 19 5 21 8.5 20.5 12c-1 4.3-8.5 9-8.5 9z"/></svg>}
function WhatsAppIcon(){return <svg viewBox="0 0 24 24" fill="currentColor" width="17" height="17" aria-hidden><path d="M12 2a10 10 0 0 0-8.6 15.1L2 22l5.1-1.3A10 10 0 1 0 12 2zm5.3 13.9c-.2.6-1.2 1.2-1.7 1.2-.4.1-1 .1-1.6-.1-.4-.1-.9-.3-1.5-.5-2.6-1.1-4.3-3.8-4.4-4-.1-.2-1.1-1.4-1.1-2.7 0-1.3.7-1.9.9-2.2.2-.3.5-.3.7-.3h.5c.2 0 .4 0 .6.4.2.5.7 1.8.8 1.9.1.1.1.3 0 .5-.1.2-.1.3-.3.5l-.4.5c-.1.1-.3.3-.1.6.2.3.8 1.3 1.7 2.1 1.2 1 2.1 1.3 2.4 1.5.3.1.5.1.7-.1.2-.2.8-.9 1-1.2.2-.3.4-.2.6-.1.3.1 1.6.8 1.9.9.3.2.5.2.5.4.1.1.1.7-.2 1.2z"/></svg>}
function ServiceIcon({n}:{n:number}){const paths=["M6 4h11a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2z","M2 6h13v12H2z","M12 3l2 5.4L19.6 10 14 11.9 12 17.4 10 11.9 4.4 10 10 8.4z","M6 3h12v18l-6-4.2L6 21z"];return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden><path d={paths[(n-1)%paths.length]}/></svg>}
const accounts=[
 {bank:"Meezan Bank",name:"Muhammad Ahmed",iban:"PK18 MEZN 0002 3101 0568 3270"},
 {bank:"JazzCash",name:"Markaz ul huda",iban:"PK37 JCMA 2606 9234 8659 6339"}
];
const allAccountDetails=accounts.map(account=>`${account.bank}\n${account.name}\nIBAN: ${account.iban}`).join("\n\n");
export default function DonatePage({language="en"}:{language?:string}){const {t}=useI18n();const [amount,setAmount]=useState(5000),[type,setType]=useState<"once"|"monthly">("once"),[name,setName]=useState(""),[toast,setToast]=useState(false);
 const impact=amount>=100000?"imp5":amount>=25000?"imp4":amount>=10000?"imp3":amount>=5000?"imp2":"imp1";
 const wa=useMemo(()=>{const msg=`Assalamu alaikum! ${name?`I am ${name}. `:""}I would like to donate PKR ${amount.toLocaleString()} (${type==="monthly"?"monthly":"one-time"}) to Markaz Al Murtaza Al Islami & Safia Islamic Institute. JazakAllahu khairan.`;return `https://wa.me/923014592661?text=${encodeURIComponent(msg)}`},[amount,type,name]);
 const copy=(v:string)=>{navigator.clipboard?.writeText(v);setToast(true);setTimeout(()=>setToast(false),1800)};
 return <><Header dark active="donate" forcedLanguage={language}/><main><section className="dn-hero"><div className="reveal"><p className="kicker gold">{t("dn_kicker")}</p><h1>{t("dn_title")}</h1><p className="dn-hero-sub">{t("dn_sub")}</p><div className="dn-verse"><p className="dn-verse-ar" lang="ar" dir="rtl">﴿ مَّثَلُ الَّذِينَ يُنفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ اللَّهِ كَمَثَلِ حَبَّةٍ أَنبَتَتْ سَبْعَ سَنَابِلَ فِي كُلِّ سُنبُلَةٍ مِّائَةُ حَبَّةٍ ﴾</p><p className="dn-verse-tr">{t("dn_verse")}<span className="verse-ref">{t("dn_verse_ref")}</span></p></div><div className="hero-ctas"><a href="#donate" className="btn btn-light">{t("nav_donate")}</a><a href="https://wa.me/923014592661" className="btn btn-outline-light">WhatsApp</a></div></div></section>
 <section className="dn-main" id="donate"><div className="dn-grid"><div className="dn-box reveal"><div className="seg"><button className={type==="once"?"active":""} onClick={()=>setType("once")}>{t("dn_once")}</button><button className={type==="monthly"?"active":""} onClick={()=>setType("monthly")}>{t("dn_monthly")}</button></div><p className="dn-label">{t("dn_amount")}</p><div className="chips">{amounts.map(a=><button key={a} className={`chip ${amount===a?"active":""}`} onClick={()=>setAmount(a)}>{a.toLocaleString()}</button>)}</div><div className="dn-range-row"><input type="range" min="500" max="200000" step="500" value={Math.min(amount,200000)} onChange={e=>setAmount(+e.target.value)}/><input id="amtInput" type="number" min="100" value={amount} onChange={e=>setAmount(Math.max(100,+e.target.value))}/></div><div className="dn-impact"><HeartIcon/><div><p className="dn-impact-label">{t("dn_impact")}</p><p>{t(impact)} {type==="monthly"&&t("dn_each_month")}</p></div></div><p className="dn-label">{t("dn_bank_title")}</p><div className="dn-accounts">{accounts.map(account=><div className="dn-bank" key={account.iban}>{[[t("dn_bank"),account.bank],[t("dn_acc_name"),account.name],[t("dn_iban_l"),account.iban]].map(([k,v])=><div className="dn-row" key={k}><span className="dn-k">{k}</span><b dir={k===t("dn_iban_l")?"ltr":undefined}>{v}</b><button className="hact" onClick={()=>copy(v)} aria-label={`Copy ${k}`}><CopyIcon/></button></div>)}</div>)}</div><button className="btn btn-ghost btn-copyall" onClick={()=>copy(allAccountDetails)}>{t("dn_copy_all")}</button><input className="dn-name" value={name} onChange={e=>setName(e.target.value)} placeholder={t("dn_your_name")}/><a className="btn btn-wa btn-send" href={wa}><WhatsAppIcon/><span>{t("dn_send")}</span></a></div>
 <div className="dn-side"><div className="dn-card reveal"><h3>{t("dn_where")}</h3>{[["dn_w_sch",40],["dn_w_teach",35],["dn_w_plat",15],["dn_w_admin",10]].map(([k,w])=><div className="bar" key={k}><div className="bar-top"><span>{t(k as string)}</span><b>{w}%</b></div><div className="bar-fill" style={{width:`${w}%`}}/></div>)}</div><div className="dn-card reveal"><h3>{t("dn_services")}</h3><div className="dn-services">{[1,2,3].map(n=><a href={sitePath("/#programs")} key={n}><ServiceIcon n={n}/><span>{t(`p${n}_title`)}</span></a>)}<a href={sitePath("/online-quran-classes")}><ServiceIcon n={4}/><span>Online Quran Classes</span></a><a href={sitePath("/#enroll")}><ServiceIcon n={3}/><span>{t("f4_t")}</span></a></div></div></div></div></section>
 <section className="dn-had"><p className="dn-had-ar" lang="ar" dir="rtl">«الصَّدَقَةُ لَا تَنْقُصُ الْمَالَ»</p><p className="dn-had-tr">{t("dn_had")}<span className="verse-ref">{t("dn_had_ref")}</span></p></section></main><div className={`toast ${toast?"show":""}`}>{t("dn_copied")}</div><Footer forcedLanguage={language}/></>}
