"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useI18n } from "./I18nProvider";
import { HonorificText } from "./SmallHonorific";
import { ENROLL_WHATSAPP_URL } from "@/lib/contact";

const I18NPath=(code:string)=>Boolean(code&&["en","ar","ur","fa","ps","sd","ks","pa","tr","az","kk","uz","id","ms","bn","hi","ta","so","sw","ha","am","fr","es","de","it","pt","ru","zh","ja","ko"].includes(code));
export function Logo(){return <img className="brand-mark" src="/images/institute-logo.png" width="640" height="640" alt="" aria-hidden="true"/>}
export function Header({dark=false,active="",languageCodes,forcedLanguage}:{dark?:boolean;active?:string;languageCodes?:readonly string[];forcedLanguage?:string}){
 const {t,lang,setLang,languages,order}=useI18n(); const available=languageCodes??order; const displayLang=forcedLanguage&&available.includes(forcedLanguage)?forcedLanguage:available.includes(lang)?lang:"en"; const tr=t; const prefix=forcedLanguage?`/${forcedLanguage}`:""; const local=(path:string)=>`${prefix}${path}`; const chooseLanguage=(code:string)=>{if(forcedLanguage){const parts=location.pathname.split("/");if(I18NPath(parts[1]))parts[1]=code;else parts.splice(1,0,code);location.href=parts.join("/")+location.search+location.hash}else setLang(code)}; const [menu,setMenu]=useState(false),[picker,setPicker]=useState(false),[q,setQ]=useState(""),[scrolled,setScrolled]=useState(false);
 useEffect(()=>{const f=()=>setScrolled(scrollY>8);addEventListener("scroll",f,{passive:true});return()=>removeEventListener("scroll",f)},[]);
 const links=[[local("/#programs"),tr("nav_programs")],[local("/#qurras"),tr("nav_qurras")],[local("/portfolio"),tr("nav_portfolio")],[local("/#features"),tr("nav_about")],[local("/#method"),tr("nav_method")],[local("/#faq"),tr("nav_faq")],[local("/#contact"),tr("nav_contact")]];
 return <><header className={`nav ${dark?"nav-dark":""} ${scrolled?"scrolled":""}`}><div className="nav-inner">
  <Link href={local("/")} className="brand"><Logo/><span className="brand-name"><HonorificText text={tr("hero_title")} language={forcedLanguage||lang}/></span></Link>
  <nav className="nav-links" aria-label="Primary">{links.map(([h,l])=><Link key={h} href={h} style={active&&h.includes(active)?{color:"var(--gold)",fontWeight:600}:undefined}>{l}</Link>)}</nav>
  <div className="nav-actions"><Link href={local("/donate")} className="btn btn-gold btn-small">{tr("nav_donate")}</Link><button className="lang-btn" onClick={()=>setPicker(!picker)} aria-haspopup="dialog" aria-expanded={picker}><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden><circle cx="12" cy="12" r="9.2"/><path d="M2.8 12h18.4M12 2.8c2.8 2.6 4 5.8 4 9.2s-1.2 6.6-4 9.2c-2.8-2.6-4-5.8-4-9.2s1.2-6.6 4-9.2z"/></svg><span>{languages[displayLang].name}</span></button><a href={ENROLL_WHATSAPP_URL} target="_blank" rel="noopener" className="btn btn-primary btn-small">{tr("nav_enroll")}</a><button className={`hamburger ${menu?"open":""}`} onClick={()=>setMenu(!menu)} aria-label="Menu" aria-expanded={menu}><span/><span/></button></div>
 </div></header>
 <div className={`mobile-menu ${menu?"open":""}`}>{links.map(([h,l])=><Link key={h} href={h} onClick={()=>setMenu(false)}>{l}</Link>)}<Link href={local("/donate")}>{t("nav_donate")}</Link><a className="btn btn-primary" href={ENROLL_WHATSAPP_URL} target="_blank" rel="noopener" onClick={()=>setMenu(false)}>{t("nav_enroll")}</a></div>
 <div className={`lang-panel ${picker?"open":""}`}><div className="lang-panel-head"><h3>{tr("lang_title")}</h3><button className="lang-close" onClick={()=>setPicker(false)}>×</button></div><input className="lang-search" value={q} onChange={e=>setQ(e.target.value)} placeholder={tr("lang_search")}/><div className="lang-grid">{available.filter(c=>(languages[c].name+languages[c].en+languages[c].region).toLowerCase().includes(q.toLowerCase())).map(c=><button key={c} className={`lang-item ${c===lang?"active":""}`} onClick={()=>{chooseLanguage(c);setPicker(false)}}><span className="lang-flag">{languages[c].flag}</span><span className="lang-names"><span className="lang-native">{languages[c].name}</span><span className="lang-en">{languages[c].en} · {languages[c].region}</span></span>{c===lang&&<span className="lang-check">✓</span>}</button>)}</div></div>
 </>;
}
export function Footer({forcedLanguage}:{forcedLanguage?:string}={}){const {t,lang}=useI18n();const tr=t;const prefix=forcedLanguage?`/${forcedLanguage}`:"";const local=(path:string)=>`${prefix}${path}`;return <footer className="footer" id="contact"><div className="footer-grid"><div className="footer-brand"><Link href={local("/")} className="brand"><Logo/><span className="brand-name"><HonorificText text={tr("hero_title")} language={forcedLanguage||lang}/></span></Link><p><HonorificText text={tr("ft_about")} language={forcedLanguage||lang}/></p></div><nav aria-label="Programs"><h4>{tr("ft_programs")}</h4>{[[1,"/hifz"],[2,"/tajweed"],[3,"/nazra"]].map(([x,path])=><Link key={x} href={String(path)}>{tr(`p${x}_title`)}</Link>)}</nav><nav aria-label="Institute"><h4>{tr("ft_links")}</h4><Link href="/online-quran-classes">Online Quran Classes</Link><Link href="/online-hifz-tajweed-institute">Online Hifz &amp; Tajweed</Link><Link href={local("/donate")}>{tr("nav_donate")}</Link><Link href={local("/portfolio")}>{tr("nav_portfolio")}</Link><Link href="/jamia-riaz-ul-jannah">Jamia Riaz-ul-Jannah</Link><Link href={local("/#qurras")}>{tr("nav_qurras")}</Link><Link href={local("/#features")}>{tr("nav_about")}</Link><Link href={local("/#method")}>{tr("nav_method")}</Link><Link href={local("/#testimonials")}>{tr("test_kicker")}</Link><Link href={local("/#faq")}>{tr("nav_faq")}</Link></nav><div><h4>{tr("ft_contact")}</h4><a href="mailto:info@markazalimurtaza.com">info@markazalimurtaza.com</a><a href="https://wa.me/923014592661">WhatsApp: +92 301 4592661</a><p className="footer-addr">{tr("ft_addr")}</p></div></div><div className="footer-bottom"><p><HonorificText text={tr("ft_rights").replace("{year}",String(new Date().getFullYear()))} language={forcedLanguage||lang}/></p></div></footer>}
